---
extends: default
  
rules:
  document-start: disable
  braces: { max-spaces-inside: 2 }
  line-length: { max: 160, level: warning }
  commas: { max-spaces-before: 1, max-spaces-after: 2 }
  colons: { max-spaces-before: 1, max-spaces-after: 2 }
  comments-indentation: disable
  indentation: { level: warning }